#------------------------------------------------------------
# Values for this workshop.
#------------------------------------------------------------

# Which carpentry is this ("swc" or "dc")?
carpentry: "swc"

# Overall title for pages.
title: "Software Carpentry Workshop"

# Contact email address.
email: nwknoblauch@gmail.com

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# What kind of thing is this ("workshop" or "lesson")?
kind: "workshop"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
repository: CreRecombinase/2017-07-24-chicago

# Sites.
amy_site: "https://amy.software-carpentry.org/workshops"
dc_site: "https://datacarpentry.org"
swc_github: "https://github.com/swcarpentry"
swc_site: "https://software-carpentry.org"
template_repo: "https://github.com/swcarpentry/styles"
example_repo: "https://github.com/swcarpentry/lesson-example"
example_site: "https://swcarpentry.github.com/lesson-example"
workshop_repo: "https://github.com/CreRecombinase/r-intermediate-altmetrics"
workshop_site: "https://CreRecombinase.github.io/r-intermediate-altmetrics"

# Surveys.
pre_survey: "https://docs.google.com/forms/d/e/1FAIpQLSc72yiQEJP17SzcCxDHDqYRPWQ1B75YWxyW66KYqww5xaq_aA/viewform?usp=send_form"
post_survey: "https://docs.google.com/forms/d/e/1FAIpQLSc9F8bMT5UIWxBS8YzbWn7XWbaSi-ycCH1snGe8xEPHdiWLyQ/viewform?usp=send_form"

# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am)
start_time: 0

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/
  extras:
    output: true

# Set the default layout for things in the episodes collection.
defaults:
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin

# Turn off built-in syntax highlighting.
highlighter: false
